python train.py \
-s ./data/buddha \
--use_colmap_poses \
--ignore_colmap_pose_alignment \
--lr_poses 0 \
--lr_exposure 0 \
--lr_depth_scale_offset 0 \
--position_lr_init 0 \
--position_lr_decay 0 \
--viewer_mode local \
--downsampling 1